# Generated by Django 4.2.3 on 2023-07-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="section",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
