# Generated by Django 4.2.3 on 2023-07-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_storeproduct_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="category",
            field=models.IntegerField(
                choices=[(1, "Shopping List"), (10, "Recipe")], default=1
            ),
        ),
    ]
