# Generated by Django 4.2.3 on 2023-07-09 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_list_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="is_deleted",
            new_name="is_hidden",
        ),
    ]
