# Generated by Django 4.2.3 on 2023-07-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_listcategory_productcategory_productunit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.listcategory",
            ),
        ),
        migrations.AddField(
            model_name="listproduct",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productunit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.storecategory",
            ),
        ),
    ]
