# Generated by Django 4.2.3 on 2023-07-11 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_auto_20230711_1550"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listcategory",
            options={"verbose_name_plural": "List Categories"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Product Categories"},
        ),
        migrations.AlterModelOptions(
            name="productunit",
            options={"verbose_name_plural": "Product Units"},
        ),
        migrations.AlterModelOptions(
            name="storecategory",
            options={"verbose_name_plural": "Store Categories"},
        ),
    ]
