# Generated by Django 4.2.3 on 2023-07-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_listcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="products",
            field=models.ManyToManyField(
                related_name="lists", through="shop.ListProduct", to="shop.product"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="products",
            field=models.ManyToManyField(
                related_name="stores", through="shop.StoreProduct", to="shop.product"
            ),
        ),
    ]
