# Generated by Django 4.2.3 on 2023-07-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_productcategory_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="shop.productcategory"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("gray", "Gray"),
                    ("black", "Black"),
                    ("brown", "Brown"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                ],
                default="white",
                max_length=10,
            ),
        ),
    ]
