# Generated by Django 4.2.3 on 2023-07-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_remove_storeproduct_aisle_storesection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeproduct",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
    ]
