# Generated by Django 4.2.3 on 2023-07-25 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_storesection_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listproduct",
            old_name="quantity_needed",
            new_name="quantity_need",
        ),
    ]
