# Generated by Django 4.2.3 on 2023-08-22 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_rename_quantity_needed_listproduct_quantity_need"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
