# Generated by Django 4.2.3 on 2023-08-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="abbreviation",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
