# Generated by Django 4.2.3 on 2023-08-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_productunit_abbreviation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listproduct",
            name="list",
        ),
        migrations.RemoveField(
            model_name="listproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="listproduct",
            name="unit",
        ),
        migrations.AddField(
            model_name="product",
            name="current_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="target_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productunit",
            ),
        ),
        migrations.DeleteModel(
            name="List",
        ),
        migrations.DeleteModel(
            name="ListCategory",
        ),
        migrations.DeleteModel(
            name="ListProduct",
        ),
    ]
