# Generated by Django 4.2.3 on 2023-08-24 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_remove_listproduct_list_remove_listproduct_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSectionType",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="storesection",
            name="section_type",
        ),
    ]
