# Generated by Django 4.2.3 on 2023-08-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_storesectiontype_remove_storesection_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesection",
            name="section_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.storesectiontype",
            ),
        ),
    ]
