# Generated by Django 4.2.3 on 2023-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0021_storesection_section_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="current_stock",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="target_quantity",
            field=models.FloatField(default=1),
        ),
    ]
