# Generated by Django 4.2.3 on 2023-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_alter_product_current_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
