# Generated by Django 4.2.3 on 2023-08-25 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pantry",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecipeCategory",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("gray", "Gray"),
                            ("black", "Black"),
                            ("brown", "Brown"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                        ],
                        default="white",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Recipe Categories",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="current_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="target_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.CreateModel(
            name="RecipeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.FloatField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.recipe"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.productunit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="shop.recipecategory"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="products",
            field=models.ManyToManyField(
                related_name="recipes", through="shop.RecipeProduct", to="shop.product"
            ),
        ),
        migrations.CreateModel(
            name="PantryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_quantity", models.FloatField(default=0)),
                ("target_quantity", models.FloatField(default=1)),
                (
                    "pantry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.pantry"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.productunit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pantry",
            name="products",
            field=models.ManyToManyField(
                related_name="pantries", through="shop.PantryProduct", to="shop.product"
            ),
        ),
    ]
