# Generated by Django 4.2.3 on 2023-08-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_pantry_recipe_recipecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pantry",
            name="name",
            field=models.CharField(default="My Pantry", max_length=50),
        ),
    ]
