# Generated by Django 4.2.3 on 2023-08-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_pantry_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
