# Generated by Django 4.2.3 on 2023-08-25 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_recipe_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pantryproduct",
            old_name="target_quantity",
            new_name="minimum_quantity",
        ),
        migrations.RenameField(
            model_name="pantryproduct",
            old_name="current_quantity",
            new_name="quantity",
        ),
    ]
