# Generated by Django 4.2.3 on 2023-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_rename_target_quantity_pantryproduct_minimum_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pantryproduct",
            name="buy_threshold",
            field=models.FloatField(blank=True, default=50, null=True),
        ),
    ]
