# Generated by Django 4.2.3 on 2023-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0028_pantryproduct_buy_threshold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pantryproduct",
            options={"ordering": ["product__name"]},
        ),
        migrations.AddField(
            model_name="pantryproduct",
            name="expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="pantryproduct",
            name="notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="pantryproduct",
            name="buy_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.5, max_digits=3, null=True
            ),
        ),
    ]
