# Generated by Django 4.2.3 on 2023-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0029_alter_pantryproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_planned",
            field=models.BooleanField(default=False),
        ),
    ]
