# Generated by Django 4.2.3 on 2023-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0030_recipe_is_favorite_recipe_is_planned"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeproduct",
            name="notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
